name: ecs-deploy

on:
  workflow_call:
    inputs:
      commit:
       required: true
       type: string
      name-repository:
         required: true
         type: string
      name-service:
        required: true
        type: string
      name-cluster:
        required: true
        type: string
      aws-region-d:
          required: true
          type: string
    secrets:
         aws-access-key-id-d:
           required: true
         aws-secret-access-key-d:
            required: true
jobs:
  ecs-deploy:
     runs-on: ubuntu-latest
     steps:
    
     - name: set credentials aws
       uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
       with:
          aws-access-key-id: ${{ secrets.aws-access-key-id-d }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key-d }}
          aws-region: ${{ inputs.aws-region-d }}
     
     - name: Checkout
       uses: actions/checkout@v2
       with:
        repository: joaov-barbosa/ecs-demo-test
            
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1

     - name: Build, tag, and push image to Amazon ECR
       env:

        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.name-repository}}
        IMAGE_TAG: ${{ inputs.commit }}
       run: |
              docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
              docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
              echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

     - name: Download task definition
       run: |
            aws ecs describe-task-definition --task-definition hello-world-app --query taskDefinition > task-definition.json
     
     - name: Deploy to Amazon ECS
       uses: aws-actions/amazon-ecs-deploy-task-definition@v1
       with:
           task-definition: task-definition.json
           service: ${{ inputs.name-service }}
           cluster: ${{ inputs.name-cluster}}
           wait-for-service-stability: true
